src/hydra/urls.py
from django.conf.urls import patterns, include, url
from tastypie.api import Api

from hydra.api import HydraResource


api = Api(api_name='v1')
api.register(HydraResource())


urlpatterns = patterns('',
    (r'^', include(api.urls)),
)

src/pecanpy/urls.py
from django.conf.urls import patterns, url
from django.utils.functional import curry
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView

class PecanView(TemplateView):
    def get_context_data(self, *args, **kwargs):
        base = super(PecanView, self).get_context_data(*args, **kwargs) or {}
        base.update({'base_url': curry(reverse, 'pecanpy_root')})
        return base

urlpatterns = patterns('',
    url(r'^',
        PecanView.as_view(template_name='pecanpy/index.html'),
        name='pecanpy_root')
)

src/zzz/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from hydra.views import ProjectView

urlpatterns = patterns('',
    url(r'^$',
        ProjectView.as_view(template_name='home.html'),
        name='home'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns('',
    url(r'^_admin/',
        include('pecanpy.urls')),
    url(r'^_api/', include('hydra.urls.api')),
    url(r'^', include('hydra.urls.slug')),
)

src/analytics/models.py
from django.db import models


class Visit(models.Model):
    when = models.DateTimeField(auto_now_add=True, db_index=True)
    project = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255, db_index=True)
    retval = models.TextField(null=True, blank=True)

src/hydra/forms.py
from django import forms

from .utils import in_whitelist


class SlugForm(forms.Form):
    project = forms.CharField(max_length=255)
    slug = forms.CharField(max_length=255)
    url = forms.URLField()

    def clean_url(self):
        url = self.cleaned_data['url']
        project = self.cleaned_data['project']
        valid, msg = in_whitelist(project, url)
        if not valid:
            raise forms.ValidationError(msg)
        return url

src/hydra/views.py
from django.core.urlresolvers import reverse
from django.conf import settings
from django.http import HttpResponseRedirect
from django.views.generic import RedirectView, TemplateView, FormView
from analytics.models import Visit

from .api import RedisProject, RedisRedirect
from .forms import SlugForm

THRESHOLD = getattr(settings, "THRESHOLD", 3)

class SlugLookupRedirectView(RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        slug = kwargs.get('slug', '')
        project = kwargs.get('project', '')
        if slug == '':
            return reverse('home')

        redirect_url = ''
        proj_obj = RedisRedirect(slug=slug, project=project)
        urls = proj_obj.get_urls()
        if urls and urls[0]['score'] > THRESHOLD:
            if len(urls) > 1:
                if urls[0]['score'] - urls[1]['score'] > THRESHOLD:
                    redirect_url = urls[0]['url']
            else:
                redirect_url = urls[0]['url']
        if not redirect_url:
            Visit.objects.create(
                project=project,
                slug=slug,
                retval=', '.join([url['url'] for url in urls]))
            return reverse('slug-details', kwargs={'slug': slug,
                                                   'project': project})

        Visit.objects.create(project=project, slug=slug, retval=redirect_url)
        return redirect_url


class SlugDetailView(FormView):
    form_class = SlugForm

    def get_context_data(self, *args, **kwargs):
        slug = self.kwargs.get('slug', '')
        project = self.kwargs.get('project', '')
        context = super(SlugDetailView, self).get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        proj_obj = RedisProject(name=project)
        context['whitelist'] = proj_obj.get_whitelist()
        redirect_obj = RedisRedirect(slug=slug, project=project)
        urls = redirect_obj.get_urls()
        if urls and urls[0]['score'] > THRESHOLD:
            context['winner'] = urls[0]['url']
        context['urls'] = urls
        context['THRESHOLD'] = THRESHOLD
        context.update(self.kwargs)
        return context

    def get_success_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug', '')
        project = self.kwargs.get('project', '')
        url = self.request.POST['url']
        redirect = RedisRedirect(slug=slug,
                                 project=project)
        redirect.incr(url)
        return url


class ProjectView(TemplateView):
    extra_context = None

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectView, self).get_context_data(*args, **kwargs)
        context['projects'] = RedisProject.all_projects()
        selected_proj = self.request.GET.get('project', "django")
        selected_slug = self.request.GET.get('slug', "")
        context['selected_project'] = selected_proj
        context['selected_slug'] = selected_slug
        context.update(kwargs)
        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            url = reverse('slug-details', kwargs={
                'project': request.POST.get('project'),
                'slug': request.POST.get('q'),
            })
            url = url if url.endswith('/') else '%s/' % url

            return HttpResponseRedirect(url)

        return super(ProjectView, self).post(request, *args, **kwargs)


class ProjectRedirect(RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        project = kwargs.get('project', '')
        return "%s?project=%s" % (reverse("home"), project)

src/pecanpy/templates/pecanpy/index.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/base.css" />
    <script type="text/javascript">BASE_URL = '{{ base_url }}';</script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/bundle.js"></script>
</head>
<body class="loading">
	
</body>
</html>

src/templates/admin.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/base.css" />
    <script type="text/javascript" src="{{ MEDIA_URL }}js/bundle.js"></script>
</head>
<body class="loading">
	
</body>
</html>

src/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ MEDIA_URL }}img/logo_32.png" />

    <link rel="stylesheet" href="{{ MEDIA_URL }}css/base.css" />
    {% block head %}
    {% endblock head %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/base.js"></script>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/frontend.css"></script>
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %}
    {% block header %}{% endblock header %}
    <div class="root">
    {% block content %}
    {% endblock content %}
    </div>
    {% endblock body %}
  </body>
</html>

src/templates/home.html
{% extends 'base.html' %}

{% block head %}
    <title>slug.in | Leaving a trail across the internet</title>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.0.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/search.js"></script>
{% endblock head %}

{% block body_class %}home{% endblock %}

{% block body %}
  <div id="landing">
    <!-- BEGIN search form -->
      <hgroup>
        <h1><span>slug</span>.in</h1>
        <p>leaving a trail across the internet</p>
      </hgroup>
      <div class="wide-search-bar">
        <div class="wide-search-bar-wrapper clearfix">
          <form action="/" method="POST">
            <select name="project" id="id_project">
              {% for project in projects %}
              <option value="{{ project }}" {% if project == selected_project %}selected{% endif %}>{{ project }}</option>
              {% endfor %}
            </select>
            <span class="text-input-wrapper">
              <input type="text" name="q" value="{{ selected_slug }}" autocomplete="off" placeholder="Your Slug" id="id_site_search_2">
            </span>
            <span class="submit-input-wrapper">
              <input type="submit" value="Slug it." id="id_search_button">
            </span>
            {% csrf_token %}
          </form>
        </div>
      </div>
      <!-- END search form -->

      <!-- BEGIN search results -->
      <div class="module" id='search_module' style="display:none">
        <div class="module-wrapper">
          <div class="module-header">
            <h3 id="id_search_title"></h3>
          </div>
          <div class="module-list">
            <div class="module-list-wrapper">
              <ul id="id_search_result">
              </ul>
            </div>
          </div>
        </div>
      </div>
    <!-- END search results -->
    <script>$('#search_module').show()</script>
    <div class="wtf">
      <div class="root" style="width:600px; text-align:left;">
      <h2 style="font-family:KnewaveOutlineRegular; text-align:center; font-size:1.5em;">WTF is Slug.in?</h2>
      <ul>
      <li>
        <p>We provide quick access to information that you care about. Go ahead and pick a project and shortcut below, and then you will be directed there.
      </li>
      <br>
      <li>
        <p>All of our shortcuts work as URLs too. So you can go to http://slug.in/*project*/*shortcut* to get to them. For example, <a href="http://slug.in/django/TIME_ZONE/"><code>http://slug.in/django/TIME_ZONE/</code></a>
       </p>
      </li>
      <br>
      <li>
        <p>
        All of the code is open source and available on <a href="https://github.com/yetizzz/zzz">GitHub</a>. It was created for the <a href="http://djangodash.com/">Django Dash</a> in 2012.
        </p>
      </li>
      </ul>
      </div>
    </div>

  </div>
{% endblock body %}

src/templates/slug-details.html
{% extends 'base.html' %}
{% load url from future %}

{% block head %}
    <title>slug.in | Slug Details</title>
{% endblock head %}

{% block body_class %}slug-details{% endblock %}

{% block header %}
      <header>
        <h1>
          <a style="font-family:KnewaveRegular" href="/"><img src="{{ MEDIA_URL }}img/logo_64.png" /><span>.in</span></a>
        </h1>
      </header>
{% endblock header %}

{% block content %}
      <h2>{{ slug }}</h2>
      <form>
      <p class="emphasis">
      Please select a URL that you think works best for <strong>{{ slug }}</strong>.
      </p>
      {% if winner %}
      <p>
        This shortcut currently pointed to: <a href="{{ winner }}">{{ winner }}</a>
      </p>
      {% else %}
      <p>
        <strong><em>/{{ project }}/{{ slug }}/</em> currently redirects to this page.</strong><br />Once a URL below has {{ THRESHOLD }} more points than the others, it will automatically be redirected at <code><a href="http://slug.in/{{ project }}/{{ slug}}/">http://slug.in/{{ project }}/{{ slug}}/</a></code>
      </p>
      {% endif %}
      </form>

      {% for url in urls %}
      {% if forloop.first %}
      <form name="increment" action="{% url 'slug-details' project slug %}" method="POST">{% csrf_token %}
        <input type="hidden" name="project" value="{{ project }}">
        <input type="hidden" name="slug" value="{{ slug }}">
        <ul>
      {% endif %}
          <li><span class="score">{{ url.score|floatformat:0 }}</span> <input type="submit" rel="increment" name="url" value="{{ url.url }}"></li>
      {% if forloop.last %}
        </ul>
      </form>
      {% endif %}
      {% endfor %}
      <form action="{% url 'slug-details' project slug %}" method="POST">{% csrf_token %}
        <input type="hidden" name="project" value="{{ project }}">
        <input type="hidden" name="slug" value="{{ slug }}">
        {% if form.url.errors %}
          <font color="red">{{ form.url.errors }}</font>
        {% endif %}
        {{ form.url }}
        <input type="submit" value="Add a new Link" />
        <h3>Allowed Sites</h3>
        <ul>
        {% for site in whitelist %}
            <p>* {{ site }}</p>
        {% endfor %}
        </ul>
      </form>

      <script src="{{ MEDIA_URL }}js/slug-detail.js"></script>
{% endblock content %}